import random

NUM_PEERS = 60
NUM_ROUNDS = 250

MIN_NEIGHBORS = 3
MAX_NEIGHBORS = 12

CONTENT_PIECES = 40

TRUST_INITIAL = 5.0
TRUST_MAX = 7.0
TRUST_MIN = 0.0

TRUST_REWARD = 0.07
TRUST_PENALTY_CORRUPT = 0.45
TRUST_PENALTY_SNOOP = 0.28
TRUST_PENALTY_UNCOOP = 0.15
TRUST_PENALTY_ACCIDENT = 0.03
TRUST_PENALTY_CRYPTO_FAIL = 0.55
TRUST_PENALTY_BAD_HMAC = 0.35
TRUST_PENALTY_BAD_PADDING = 0.40

TRUST_THRESHOLD = 5.0
ISOLATION_THRESHOLD = 3.0
REWIRING_THRESHOLD = 4.0

PERCENT_MALICIOUS = 0.12
PERCENT_SNOOPER = 0.10
PERCENT_UNCOOP = 0.10
PERCENT_HONEST = 0.68

CORRUPTION_PROB = 0.50
SNOOP_PROB = 0.30
REFUSE_PROB = 0.35
ACCIDENT_PROB = 0.02

CRYPTO_KEY_ROTATION_INTERVAL = 15
CRYPTO_FAIL_PROB = 0.08

LOG_TRUST = True
LOG_EVENTS = True
LOG_NEIGHBORS = True
LOG_CONTENT = True
LOG_CRYPTO = True

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
